Data_Processing:
  budget: 20
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  nice: 0
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
Velodyne HDL-32e:
  calibration: /home/katou01/.autoware/depth/calib-20170116.yml
  calibration1: /home/katou01/.autoware/depth/calib-20170116.yml
astar_navi:
  use_back: false
  waypoint_velocity_kmph: 5.0
button_input1: {}
button_input100: {}
button_input101: {}
button_input11:
  file: Please Set Calibration File
button_input4: {}
calibration_publisher:
  camera_id: ''
  file: ''
  publish_camera_info: false
  publish_extrinsic_mat: true
  register_lidar2camera_tf: true
  solo_camera: true
can_listener:
  channel: 0
car_dpm:
  Lambda: 10
  group_threshold: 0.1
  num_bins: 9
  num_cells: 8
  score_threshold: -0.5
car_fusion:
  car: true
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
  pedestrian: false
  sync: false
car_kf:
  camera_id: ''
  car: true
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  pedestrian: false
  percentage_of_overlapping: 0.0
  sync: false
  use_orb: 0
detection_qs:
  file: ''
localization_qs:
  file: /home/katou01/.autoware/my_launch/my_localization.launch
map_qs:
  file: /home/katou01/.autoware/my_launch/my_map.launch
mission_planning_qs:
  file: ''
motion_planning_qs:
  file: ''
pcd_binarizer:
  path_pcd_binarizer: ''
pcd_filter:
  leaf_size: 0.2
  path_pcd_filter: ''
pedestrian_dpm:
  Lambda: 10
  group_threshold: 0.3
  num_bins: 9
  num_cells: 8
  score_threshold: 0.6
pedestrian_fusion:
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
pedestrian_kf:
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  percentage_of_overlapping: 0.0
  use_orb: 0
play_rosbag_play:
  confirm: 0
  file: /home/katou01/.autoware/autoware-201701171120.bag
  rate: 9.0
  repeat: false
  start: 0
point_cloud:
  path_area_list: None
  path_area_list_cmd_param: null
  path_pcd: ''
  scene_num: noupdate
points_image:
  camera_id: ''
  sync: false
pos_downloader:
  db_host_name: db3.ertl.jp
  db_port: 5678
  now: false
  show_my_pose: false
  sshport: 22
  sshprivatekey: /home/katou01/.ssh/id_rsa
  sshpubkey: /home/katou01/.ssh/id_rsa.pub
  sshtunnelhost: localhost
  username: ''
sensing_qs:
  file: ''
setup_tf:
  frame_id: /base_link
  localizer_cmd_param: /velodyne
  localizer_rosparam: velodyne
  period_in_ms: 10
  pitch: 0.0
  roll: 0.0
  x: 1.2
  y: 0.0
  yaw: 0.0
  z: 2.0
tf:
  file: ''
vector_map:
  path_vec: ''
vehicle_info:
  info_path: ''
vehicle_model:
  model_path: ''
velocity_set:
  budget: 20
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  deceleration: 1.05
  deceleration_range: 1.7
  detection_height_bottom: -1.5
  detection_height_top: 0.1
  detection_range: 1.3
  nice: 0
  others_distance: 15.8
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
  temporal_waypoints_size: 103.8
  threshold_points: 15
  use_crosswalk_detection: false
  velocity_change_limit: 15.0
virtual_scan_image:
  camera_id: ''
  sync: false
